from pathlib import Path

from models import Result, Status, ValidationReport


PYTHON_VERSION = "3.12.10"
PIP_VERSION = "25.0.1"
PYTEST_VERSION = "9.1.1"


def _file_contents(project_name: str) -> dict[str, str]:
    distribution_name = project_name.replace("_", "-")

    return {
        ".python-version": f"{PYTHON_VERSION}\n",

        ".gitignore": """\
.venv/
__pycache__/
*.py[cod]
.env
.pytest_cache/
*.egg-info/
build/
""",

        ".env.example": """\
# Add environment variables required by the project here.
""",

        ".vscode/settings.json": """\
{
    "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python"
}
""",

        "README.md": f"""\
# {distribution_name}

Python project generated by pyprojectgen.

## Development setup

Run:

```bash
./scripts/bootstrap.sh
```

The bootstrap script creates the virtual environment, installs the
required dependencies, installs the project in editable mode, and runs
the test suite.
""",

        "pyproject.toml": f"""\
[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{distribution_name}"
version = "0.1.0"
requires-python = "=={PYTHON_VERSION}"
dependencies = []

[project.optional-dependencies]
test = [
    "pytest=={PYTEST_VERSION}",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
""",

        "requirements-bootstrap.txt": f"""\
pip=={PIP_VERSION}
""",

        "requirements.txt": f"""\
iniconfig==2.3.0
packaging==26.3
pluggy==1.6.0
Pygments==2.21.0
pytest=={PYTEST_VERSION}
""",

        f"src/{project_name}/__init__.py": "",

        "tests/test_import.py": f"""\
def test_import():
    import {project_name}

    assert {project_name} is not None
""",

        "scripts/bootstrap.sh": """\
#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${PROJECT_ROOT}"

if [ ! -f ".python-version" ]; then
    echo "[ERROR] .python-version not found"
    exit 1
fi

REQUIRED_VERSION="$(tr -d '[:space:]' < .python-version)"

if [ -z "${REQUIRED_VERSION}" ]; then
    echo "[ERROR] .python-version is empty"
    exit 1
fi

MAJOR_MINOR="${REQUIRED_VERSION%.*}"

PYTHON_CANDIDATES=(
    "python${MAJOR_MINOR}"
    "python3"
    "/Library/Frameworks/Python.framework/Versions/${MAJOR_MINOR}/bin/python3"
)

PYTHON_EXECUTABLE=""

for candidate in "${PYTHON_CANDIDATES[@]}"; do
    if command -v "${candidate}" >/dev/null 2>&1; then
        candidate_path="$(command -v "${candidate}")"
    elif [ -x "${candidate}" ]; then
        candidate_path="${candidate}"
    else
        continue
    fi

    candidate_version="$(
        "${candidate_path}" -c \
        'import platform; print(platform.python_version())'
    )"

    if [ "${candidate_version}" = "${REQUIRED_VERSION}" ]; then
        PYTHON_EXECUTABLE="${candidate_path}"
        break
    fi
done

if [ -z "${PYTHON_EXECUTABLE}" ]; then
    echo "[ERROR] Python ${REQUIRED_VERSION} not found"
    exit 1
fi

echo "[OK] Using Python ${REQUIRED_VERSION}: ${PYTHON_EXECUTABLE}"

if [ ! -d ".venv" ]; then
    "${PYTHON_EXECUTABLE}" -m venv .venv
    echo "[CREATE] Virtual environment: .venv"
else
    echo "[SKIP] Virtual environment already exists: .venv"
fi

source .venv/bin/activate

VENV_VERSION="$(
    python -c 'import platform; print(platform.python_version())'
)"

if [ "${VENV_VERSION}" != "${REQUIRED_VERSION}" ]; then
    echo "[ERROR] .venv uses Python ${VENV_VERSION}; expected ${REQUIRED_VERSION}"
    exit 1
fi

python -m pip install -r requirements-bootstrap.txt
python -m pip install -r requirements.txt
python -m pip install -e ".[test]"

python -m pytest

echo "[OK] Bootstrap complete"
""",
    }


def plan_project_files(
    project_root: Path,
    project_name: str,
) -> ValidationReport:
    results: list[Result] = []

    for relative_path, expected_content in _file_contents(project_name).items():
        path = project_root / relative_path

        if not path.exists():
            results.append(
                Result(
                    Status.CREATE,
                    f"File: {path}",
                )
            )
            continue

        if not path.is_file():
            results.append(
                Result(
                    Status.ERROR,
                    f"Expected file but found another object: {path}",
                )
            )
            continue

        current_content = path.read_text(encoding="utf-8")

        if current_content == expected_content:
            results.append(
                Result(
                    Status.SKIP,
                    f"File already exists and matches: {path}",
                )
            )
        else:
            results.append(
                Result(
                    Status.ERROR,
                    f"Existing file differs from generated content: {path}",
                )
            )

    return ValidationReport(results=tuple(results))


def create_project_files(
    project_root: Path,
    project_name: str,
) -> ValidationReport:
    plan = plan_project_files(
        project_root=project_root,
        project_name=project_name,
    )

    if plan.has_errors:
        return plan

    results: list[Result] = []

    for relative_path, content in _file_contents(project_name).items():
        path = project_root / relative_path

        if path.exists():
            results.append(
                Result(
                    Status.SKIP,
                    f"File already exists and matches: {path}",
                )
            )
            continue

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

        if relative_path == "scripts/bootstrap.sh":
            path.chmod(0o755)

        results.append(
            Result(
                Status.CREATE,
                f"File: {path}",
            )
        )

    return ValidationReport(results=tuple(results))